name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run Test Suites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  publish-npm:
    name: Build Package & Publish to npm
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
